"use client";
import { useState } from "react";
import { useParams,useSearchParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft,Calculator,CheckCircle2,Lightbulb } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useApp } from "@/components/app-provider";
type Step={step:number;find:string;formula:string;why:string;symbols:Array<{symbol:string;meaning:string}>;substitution:string;answer:string};
type Solution={target:{symbol:string;meaning:string;unit:string};givenValues:Array<{symbol:string;meaning:string;value:string;unit:string}>;roadmap:Step[];finalAnswer:string;patternToRemember:string;warning?:string};
export default function Practice(){const{id}=useParams<{id:string}>(),topicName=useSearchParams().get("topic")||"Practice",{data}=useApp(),course=data.courses.find(c=>c.id===id),topic=course?.analysis?.topics.find(t=>t.name===topicName);const[question,setQuestion]=useState(""),[solution,setSolution]=useState<Solution|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");async function solve(q:string){if(!course)return;setQuestion(q);setBusy(true);setSolution(null);setError("");try{const r=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,courseCode:course.code,courseTitle:course.title,materials:course.materials})});const v=await r.json();if(!r.ok)throw new Error(v.error);setSolution(v)}catch(e){setError(e instanceof Error?e.message:"Tutor failed.")}finally{setBusy(false)}}if(!course)return null;return <AppShell eyebrow={`${course.code} · GUIDED PRACTICE`} title={topicName} action={<Link className="back-link" href={`/courses/${id}`}><ArrowLeft/>Course map</Link>}><div className="practice-layout"><aside className="practice-questions"><h2>Past questions</h2><p>Choose one. Olodo exposes the entire formula route.</p>{topic?.questions.map((q,i)=><button className={question===q.question?"selected":""} key={i} onClick={()=>solve(q.question)}><span>{q.year||`Q${i+1}`}</span>{q.question}</button>)}</aside><section>{busy&&<div className="lesson-welcome"><Calculator/><h2>Mapping every missing value...</h2></div>}{error&&<p className="form-error">{error}</p>}{!busy&&!solution&&<div className="lesson-welcome"><Calculator/><h2>Select a question to begin.</h2><p>No copying and pasting required.</p></div>}{solution&&<div className="solution"><header><div><small>WHAT ARE WE FINDING?</small><h2>{solution.target.meaning} <span>{solution.target.symbol}</span></h2></div><CheckCircle2/></header>{solution.warning&&<p className="solution-warning">{solution.warning}</p>}<section className="given-values"><h3>Given values</h3><div>{solution.givenValues.map((v,i)=><article key={i}><b>{v.symbol}</b><span>{v.meaning}</span><strong>{v.value} {v.unit}</strong></article>)}</div></section><section className="roadmap"><h3>Formula roadmap</h3>{solution.roadmap.map(s=><article key={s.step}><span>{s.step}</span><div><small>FIND {s.find}</small><h4>{s.formula}</h4><p>{s.why}</p><dl>{s.symbols.map(x=><div key={x.symbol}><dt>{x.symbol}</dt><dd>{x.meaning}</dd></div>)}</dl><div className="substitution"><em>INPUT THE VALUES</em><b>{s.substitution}</b></div><div className="step-answer"><em>STEP ANSWER</em><b>{s.answer}</b></div></div></article>)}</section><footer className="final-answer"><small>STRAIGHT ANSWER</small><h2>{solution.finalAnswer}</h2></footer><div className="remember"><Lightbulb/><p><b>Pattern to remember</b>{solution.patternToRemember}</p></div></div>}</section></div></AppShell>}
