"use client";
import { FormEvent,useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft,ArrowRight,BookMarked,Brain,CheckCircle2,Quote } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useApp } from "@/components/app-provider";
type Lesson={topic:string;startFromZero:string;keyIdeas:Array<{title:string;explanation:string;example:string}>;definitions:Array<{term:string;meaning:string}>;examAnswer:{introduction:string;body:string[];conclusion:string};memoryHook:string;checkQuestions:Array<{question:string;answer:string}>};
export default function TheoryLesson(){const{id}=useParams<{id:string}>(),{data}=useApp(),course=data.courses.find(c=>c.id===id);const[topic,setTopic]=useState(""),[lesson,setLesson]=useState<Lesson|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");async function teach(e:FormEvent){e.preventDefault();if(!course)return;setBusy(true);setError("");try{const response=await fetch("/api/theory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,courseCode:course.code,courseTitle:course.title,materials:course.materials})});const value=await response.json();if(!response.ok)throw new Error(value.error);setLesson(value)}catch(e){setError(e instanceof Error?e.message:"Lesson failed.")}finally{setBusy(false)}}if(!course)return null;return <AppShell eyebrow={`${course.code} · THEORY MENTOR`} title={course.title} action={<Link className="back-link" href={`/courses/${id}`}><ArrowLeft/>Calculations</Link>}><div className="theory-shell"><aside><BookMarked/><h3>Theory rescue mode</h3><p>Understand it in plain language, then learn how to write it for marks.</p><ol><li>Start from zero</li><li>Know the key ideas</li><li>Learn the definitions</li><li>Build an exam answer</li></ol></aside><section><form className="question-box" onSubmit={teach}><label>TOPIC OR THEORY QUESTION</label><textarea required value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Explain the working principle of a transformer and list its losses."/><button disabled={busy}>{busy?"Building your lesson...":"Teach this from scratch"}<ArrowRight/></button>{error&&<p className="form-error">{error}</p>}</form>{lesson&&<article className="theory-lesson"><header><Brain/><div><small>START FROM ZERO</small><h2>{lesson.topic}</h2></div></header><p className="zero-explanation">{lesson.startFromZero}</p><section><h3>Key ideas</h3>{lesson.keyIdeas.map((idea,i)=><div className="key-idea" key={idea.title}><span>0{i+1}</span><div><h4>{idea.title}</h4><p>{idea.explanation}</p><small>Example: {idea.example}</small></div></div>)}</section><section><h3>Definitions examiners expect</h3><div className="definition-grid">{lesson.definitions.map(d=><div key={d.term}><b>{d.term}</b><span>{d.meaning}</span></div>)}</div></section><section className="exam-answer"><Quote/><small>EXAM-READY ANSWER</small><p>{lesson.examAnswer.introduction}</p>{lesson.examAnswer.body.map((p,i)=><p key={i}>{p}</p>)}<p>{lesson.examAnswer.conclusion}</p></section><div className="memory-hook"><Brain/><p><b>Memory hook</b>{lesson.memoryHook}</p></div><section><h3>Check yourself</h3>{lesson.checkQuestions.map((q,i)=><details key={i}><summary>{q.question}</summary><p><CheckCircle2/>{q.answer}</p></details>)}</section></article>}</section></div></AppShell>}
