"use client";
import { ChangeEvent, FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, FileUp, Plus, X } from "lucide-react";
import { Brand } from "@/components/brand";
import { useApp } from "@/components/app-provider";
import { CourseRecord } from "@/lib/store";
import { GoogleDrivePicker } from "@/components/google-drive-picker";
const steps=["Your degree","Courses","Exam timetable","Materials","Study rhythm"],days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export default function Onboarding(){const router=useRouter(),{data,update}=useApp();const[step,setStep]=useState(0),[courses,setCourses]=useState<CourseRecord[]>(data.courses),[code,setCode]=useState(""),[title,setTitle]=useState(""),[school,setSchool]=useState(data.school),[degree,setDegree]=useState(data.degree),[level,setLevel]=useState(data.level),[hours,setHours]=useState(data.availableHours),[mode,setMode]=useState(data.studyMode),[selectedDays,setSelectedDays]=useState(data.studyDays),[timetable,setTimetable]=useState(data.timetableFile);
const add=()=>{if(code.trim()){setCourses([...courses,{id:crypto.randomUUID(),code:code.toUpperCase(),title:title||"Untitled course",examDate:"",estimatedHours:12,completedHours:0,materials:[]}]);setCode("");setTitle("")}};
const addFiles=(e:ChangeEvent<HTMLInputElement>)=>{const names=Array.from(e.target.files||[]).map(f=>f.name),first=courses[0];if(first)setCourses(courses.map(c=>c.id===first.id?{...c,materials:[...c.materials,...names]}:c))};
const addDriveFiles=(files:Array<{name:string}>)=>{const first=courses[0];if(first)setCourses(courses.map(c=>c.id===first.id?{...c,materials:[...c.materials,...files.map(f=>f.name)]}:c))};
function next(e:FormEvent){e.preventDefault();if(step<4)setStep(step+1);else{update({school,degree,level,courses,timetableFile:timetable,availableHours:hours,studyMode:mode,studyDays:selectedDays,onboardingComplete:true});router.push("/dashboard")}}
return <main className="onboarding"><aside className="setup-side"><Brand light/><div className="setup-progress">{steps.map((s,i)=><button className={i===step?"current":i<step?"done":""} key={s} onClick={()=>i<=step&&setStep(i)}><span>{i<step?<Check/>:i+1}</span>{s}</button>)}</div><p>About 4 minutes. Change anything later.</p></aside><section className="setup-main"><form onSubmit={next} className="setup-card"><div className="mobile-step">STEP {step+1} OF 5</div>
{step===0&&<><p className="step-label">LET’S START WITH CONTEXT</p><h1>What are you studying?</h1><p className="lead">This helps Olodo recognise expected depth and missing prerequisites.</p><div className="field-grid"><label className="wide">School<input required value={school} onChange={e=>setSchool(e.target.value)} placeholder="University of Lagos"/></label><label>Degree<input required value={degree} onChange={e=>setDegree(e.target.value)} placeholder="Electrical Engineering"/></label><label>Level<select required value={level} onChange={e=>setLevel(e.target.value)}><option value="">Choose level</option>{[100,200,300,400,500].map(x=><option key={x}>{x} Level</option>)}</select></label><label>Minimum target<select value={data.targetGrade} onChange={e=>update({targetGrade:e.target.value})}><option>C</option><option>B</option><option>A</option></select></label></div></>}
{step===1&&<><p className="step-label">BUILD THIS SEMESTER</p><h1>Add the courses you need to survive.</h1><p className="lead">Use the same course codes shown on your timetable.</p><div className="course-entry"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="MTH 201"/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Engineering Mathematics"/><button type="button" onClick={add}><Plus/>Add</button></div><div className="added-list">{courses.map(c=><div key={c.id}><span><b>{c.code}</b>{c.title}</span><button type="button" onClick={()=>setCourses(courses.filter(x=>x.id!==c.id))}><X/></button></div>)}{!courses.length&&<div className="empty-inline">Add at least one course to continue.</div>}</div></>}
{step===2&&<><p className="step-label">SET THE DEADLINES</p><h1>Upload your exam timetable.</h1><p className="lead">Use a PDF, screenshot, or clear phone photo. You can confirm the extracted dates later.</p><label className="dropzone"><input type="file" accept=".pdf,image/*" onChange={e=>setTimetable(e.target.files?.[0]?.name||"")}/><FileUp/><strong>{timetable||"Choose exam timetable"}</strong><span>PDF, PNG or JPG</span></label></>}
{step===3&&<><p className="step-label">PAST QUESTIONS FIRST</p><h1>Add the materials that reveal the exam.</h1><p className="lead">Start with past questions. Notes and textbooks can follow.</p><label className="dropzone"><input multiple type="file" accept=".pdf,image/*,.doc,.docx" onChange={addFiles}/><FileUp/><strong>Choose course materials</strong><span>Multiple files welcome</span></label><div className="import-options"><button type="button">Open folder</button><GoogleDrivePicker onFilesSelected={addDriveFiles}/></div><p className="file-count">{courses.reduce((n,c)=>n+c.materials.length,0)} files ready</p></>}
{step===4&&<><p className="step-label">MAKE THE PLAN REALISTIC</p><h1>How much focused time can you actually give?</h1><p className="lead">We schedule estimated work, not every day until the exam.</p><div className="hours-control"><button type="button" onClick={()=>setHours(Math.max(.5,hours-.5))}>−</button><strong>{hours}<span>hours / day</span></strong><button type="button" onClick={()=>setHours(Math.min(12,hours+.5))}>+</button></div><label className="section-label">Available days</label><div className="day-picker">{days.map(d=><button type="button" className={selectedDays.includes(d)?"selected":""} onClick={()=>setSelectedDays(selectedDays.includes(d)?selectedDays.filter(x=>x!==d):[...selectedDays,d])} key={d}>{d}</button>)}</div><label className="section-label">Planning style</label><div className="mode-grid"><button type="button" className={mode==="sprint"?"selected":""} onClick={()=>setMode("sprint")}><b>Course Sprint</b><span>One pass path at a time.</span></button><button type="button" className={mode==="timetable"?"selected":""} onClick={()=>setMode("timetable")}><b>Timetable</b><span>Split time across courses.</span></button></div></>}
<footer className="setup-actions">{step?<button type="button" className="back" onClick={()=>setStep(step-1)}><ArrowLeft/>Back</button>:<span/>}<button className="button" disabled={step===1&&!courses.length}>{step===4?"Build my dashboard":"Continue"}<ArrowRight/></button></footer></form></section></main>}
