import { NextResponse } from "next/server";
import { z } from "zod";
import { createAiClient } from "@/lib/ai/client";
import { env } from "@/lib/env";
export const runtime="nodejs";
const textSchema=z.object({text:z.string().min(2).max(120000)});
async function readWithQwenOcr(file:File){if(file.size>20*1024*1024)throw new Error("This course form is over 20 MB. Compress or split it, then upload again.");const base64=Buffer.from(await file.arrayBuffer()).toString("base64"),dataUrl=`data:${file.type||"application/pdf"};base64,${base64}`;const response=await fetch(`${env.AI_BASE_URL}/responses`,{method:"POST",headers:{Authorization:`Bearer ${env.AI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:env.OCR_MODEL||"qwen3.5-ocr",input:[{role:"user",content:[{type:"input_file",filename:file.name,file_data:dataUrl},{type:"input_text",text:"Extract all text from this university course registration form. Preserve course codes, course titles, tables and exam dates. Return plain text only."}]}]})});const value=await response.json();if(!response.ok)throw new Error(value?.error?.message||"Qwen OCR could not read this file.");const direct=value.output_text as string|undefined,nested=(value.output as Array<{content?:Array<{text?:string}>}>|undefined)?.flatMap(item=>item.content||[]).map(item=>item.text||"").join("\n"),text=direct||nested;if(!text)throw new Error("OCR completed but no readable text was found. Try a clearer scan.");return text;}
async function extractCourses(text:string){const response=await createAiClient().chat.completions.create({model:env.AI_MODEL||"qwen-plus",response_format:{type:"json_object"},messages:[{role:"system",content:"Extract academic courses from the supplied university course form. Return JSON only: {\"courses\":[{\"code\":\"MTH 201\",\"title\":\"Engineering Mathematics\",\"examDate\":\"ISO date when explicit, otherwise empty\"}]}. Remove duplicates. Never invent titles or dates; use 'Course title unavailable' when a title is genuinely absent."},{role:"user",content:text.slice(0,120000)}]});const content=response.choices[0]?.message?.content;if(!content)throw new Error("Qwen returned no courses.");return JSON.parse(content);}
export async function POST(request:Request){try{if(!env.AI_API_KEY)throw new Error("Qwen is not configured on the server.");const contentType=request.headers.get("content-type")||"";let text="";if(contentType.includes("multipart/form-data")){const form=await request.formData(),file=form.get("file");if(!(file instanceof File))throw new Error("Choose a course-form file first.");const isText=file.type.startsWith("text/")||/\.(txt|csv|md)$/i.test(file.name);text=isText?await file.text():await readWithQwenOcr(file);}else{text=textSchema.parse(await request.json()).text;}return NextResponse.json(await extractCourses(text));}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Extraction failed."},{status:400})}}
