"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent,useState } from "react";
import { ArrowRight,Eye,EyeOff } from "lucide-react";
import { Brand } from "@/components/brand";
import { useApp } from "@/components/app-provider";
import { createBrowserSupabaseClient,isSupabaseConfigured } from "@/lib/supabase/client";
export function AuthForm({mode}:{mode:"login"|"signup"}){const router=useRouter(),{data,ready,update}=useApp();const[name,setName]=useState(data.name),[email,setEmail]=useState(data.email),[password,setPassword]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const signup=mode==="signup";
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!ready)return;setBusy(true);setError("");if(isSupabaseConfigured()){const supabase=createBrowserSupabaseClient();const result=signup?await supabase.auth.signUp({email:email.trim(),password,options:{data:{name:name.trim()}}}):await supabase.auth.signInWithPassword({email:email.trim(),password});if(result.error){setError(result.error.message);setBusy(false);return}if(signup&&!result.data.session){setError("Check your email to confirm your account, then log in.");setBusy(false);return}}const destination=data.onboardingComplete?"/dashboard":"/onboarding";update({authenticated:true,name:name.trim()||email.split("@")[0],email:email.trim()});router.replace(destination);setBusy(false)}
return <main className="auth-page"><section className="auth-aside"><Brand light/><div><span className="kicker">ZERO SHAME. CLEAR STEPS.</span><h1>Start where you are.<br/>Pass what&apos;s ahead.</h1><p>Your course materials become a private, past-question-first study plan built around the hours you actually have.</p></div><blockquote>&ldquo;Tell me what to learn, why I need it, and exactly what formula comes next.&rdquo;</blockquote></section><section className="auth-main"><div className="auth-card"><p className="step-label">{signup?"CREATE YOUR ACCOUNT":"WELCOME BACK"}</p><h2>{signup?"Let&apos;s build your pass plan.":"Continue your mission."}</h2><p className="muted">{signup?"Your cloud account keeps your plan across devices.":"Log in to continue your saved pass plan."}</p><form onSubmit={submit}>{signup&&<label>First name<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<div className="password-field"><input required minLength={6} type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="form-error">{error}</p>}<button className="button full" disabled={!ready||busy}>{busy?"Please wait...":signup?"Continue to setup":"Log in"}<ArrowRight/></button></form><p className="auth-switch">{signup?"Already have an account?":"New to Olodo AI?"} <Link href={signup?"/login":"/signup"}>{signup?"Log in":"Create account"}</Link></p></div></section></main>}
