"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useRef, useState } from "react";
import { Cloud, LoaderCircle } from "lucide-react";
type DriveFile={id:string;name:string;mimeType:string;url?:string};
type PickerResult={action:string;docs?:DriveFile[]};
declare global{interface Window{google?:{accounts:{oauth2:{initTokenClient:(c:Record<string,unknown>)=>{requestAccessToken:(o?:Record<string,unknown>)=>void}}};picker:{Action:{PICKED:string};DocsView:new()=>{setIncludeFolders:(v:boolean)=>unknown;setSelectFolderEnabled:(v:boolean)=>unknown};Feature:{MULTISELECT_ENABLED:string};PickerBuilder:new()=>{addView:(v:unknown)=>any;enableFeature:(v:string)=>any;setOAuthToken:(v:string)=>any;setDeveloperKey:(v:string)=>any;setCallback:(v:(d:PickerResult)=>void)=>any;build:()=>{setVisible:(v:boolean)=>void}}}};gapi?:{load:(n:string,c:()=>void)=>void}}}
function loadScript(src:string,id:string){return new Promise<void>((resolve,reject)=>{const found=document.getElementById(id)as HTMLScriptElement|null;if(found?.dataset.loaded==="true")return resolve();const script=found??document.createElement("script");script.id=id;script.src=src;script.async=true;script.onload=()=>{script.dataset.loaded="true";resolve()};script.onerror=()=>reject(new Error("Could not load Google Drive."));if(!found)document.head.appendChild(script)})}
export function GoogleDrivePicker({onFilesSelected}:{onFilesSelected:(files:DriveFile[])=>void}){const[status,setStatus]=useState<"loading"|"ready"|"opening"|"error">("loading"),[message,setMessage]=useState("");const pickerReady=useRef(false);const clientId=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,apiKey=process.env.NEXT_PUBLIC_GOOGLE_API_KEY;
useEffect(()=>{if(!clientId||!apiKey){setStatus("error");setMessage("Google Drive needs configuration.");return}Promise.all([loadScript("https://accounts.google.com/gsi/client","google-identity-script"),loadScript("https://apis.google.com/js/api.js","google-api-script")]).then(()=>window.gapi?.load("picker",()=>{pickerReady.current=true;setStatus("ready")})).catch((e:Error)=>{setStatus("error");setMessage(e.message)})},[apiKey,clientId]);
function open(){if(!clientId||!apiKey||!window.google||!pickerReady.current)return;setStatus("opening");setMessage("");const token=window.google.accounts.oauth2.initTokenClient({client_id:clientId,scope:"https://www.googleapis.com/auth/drive.file",callback:(r:{access_token?:string;error?:string})=>{if(!r.access_token||r.error){setStatus("ready");setMessage("Google access was not granted.");return}const view=new window.google!.picker.DocsView();view.setIncludeFolders(true);view.setSelectFolderEnabled(false);new window.google!.picker.PickerBuilder().addView(view).enableFeature(window.google!.picker.Feature.MULTISELECT_ENABLED).setOAuthToken(r.access_token).setDeveloperKey(apiKey).setCallback((d:PickerResult)=>{if(d.action===window.google!.picker.Action.PICKED&&d.docs)onFilesSelected(d.docs);setStatus("ready")}).build().setVisible(true)},error_callback:()=>{setStatus("ready");setMessage("Google sign-in was closed.")}});token.requestAccessToken({prompt:"consent"})}
return <div className="drive-control"><button type="button" onClick={open} disabled={status!=="ready"}>{status==="loading"||status==="opening"?<LoaderCircle className="spin"/>:<Cloud/>}{status==="loading"?"Loading Drive...":status==="opening"?"Opening Drive...":"Connect Google Drive"}</button>{message&&<small>{message}</small>}{status==="error"&&<small>Add NEXT_PUBLIC_GOOGLE_CLIENT_ID and NEXT_PUBLIC_GOOGLE_API_KEY to .env.local.</small>}</div>}
